# Generated by Django 6.0.1 on 2026-02-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_team_slot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('purple', 'Purple'), ('orange', 'Orange')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
