# Generated by Django 6.0.1 on 2026-02-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_team_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
