# Generated by Django 6.0.1 on 2026-02-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_team_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
