# Generated by Django 6.0.1 on 2026-02-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_player_aces_player_blocks_player_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='games_played',
        ),
        migrations.AddField(
            model_name='player',
            name='fouls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='aces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='blocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
