# Generated by Django 6.0.1 on 2026-02-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_remove_player_games_played_player_fouls_player_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='waiver_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
