# Generated by Django 6.0.1 on 2026-02-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_team_waiver_agreed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='waiver_agreed',
            new_name='waiver_accepted',
        ),
        migrations.AddField(
            model_name='team',
            name='waiver_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
