# Generated by Django 6.0.1 on 2026-02-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_rename_waiver_agreed_team_waiver_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='waiver_accepted',
        ),
        migrations.RemoveField(
            model_name='team',
            name='waiver_accepted_at',
        ),
    ]
