# Generated by Django 6.0.1 on 2026-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_team_waiver_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='waiver_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='waiver_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
