# Generated by Django 6.0.1 on 2026-02-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_team_waiver_agreed_team_waiver_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='emergency_contact_phone',
        ),
    ]
