# Generated by Django 6.0.1 on 2026-02-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_remove_player_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteerapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_firstname', models.CharField(max_length=25)),
                ('volunteer_lastname', models.CharField(max_length=25)),
                ('volunteer_email', models.EmailField(max_length=254, unique=True)),
                ('volunteer_phone', models.CharField(max_length=15)),
                ('volunteer_age', models.PositiveIntegerField(blank=True, null=True)),
                ('volunteer_role', models.CharField(max_length=50)),
                ('why_interested', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
