# Generated by Django 6.0.1 on 2026-02-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_volunteerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
