# Generated by Django 6.0.1 on 2026-02-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_alter_volunteerapplication_volunteer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player_count',
            field=models.IntegerField(default=6),
        ),
    ]
