# Generated by Django 6.0.1 on 2026-02-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_team_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
    ]
