# Generated by Django 6.0.1 on 2026-02-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_alter_player_contact_phone_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain_email',
            field=models.EmailField(max_length=254),
        ),
    ]
