# Generated by Django 6.0.1 on 2026-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_alter_team_captain_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
