# Generated by Django 6.0.1 on 2026-03-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='spectator_range',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
