# Generated by Django 6.0.1 on 2026-05-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_team_spectator_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain_phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer_phone',
            field=models.CharField(max_length=25),
        ),
    ]
