# Generated by Django 6.0.1 on 2026-05-07 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_alter_team_captain_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('skill_level', models.CharField(max_length=20)),
                ('player_type', models.CharField(choices=[('solo', 'Solo Player'), ('group', 'Group Looking')], max_length=20)),
                ('instagram', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_progress', 'In Progress'), ('filled', 'Filled')], default='available', max_length=20)),
                ('edit_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
