# Generated by Django 6.0.1 on 2026-05-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_freeagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeagent',
            name='skill_level',
        ),
    ]
