# Generated by Django 6.0.1 on 2026-05-11 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_remove_freeagent_skill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(upload_to='creators/')),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('media_file', models.FileField(upload_to='media_gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_thumbnails/')),
                ('category', models.CharField(choices=[('2024', '2024 Basketball'), ('2026', '2026 Volleyball'), ('bts', 'Behind The Scenes'), ('creative', 'Creative Showcase')], max_length=20)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.creator')),
            ],
        ),
    ]
