# Generated by Django 6.0.1 on 2026-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_alter_creator_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='round_name',
            field=models.CharField(choices=[('pool', 'Pool Play'), ('quarter', 'Quarter Final'), ('semi', 'Semi Final'), ('final', 'Final')], default='pool', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_score',
            field=models.IntegerField(default=0),
        ),
    ]
