# Generated by Django 6.0.1 on 2026-06-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_match_is_finished_match_is_live_match_round_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='creator',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='creators',
            field=models.ManyToManyField(related_name='media_items', to='tournament.creator'),
        ),
    ]
