# Generated by Django 6.0.1 on 2026-06-07 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_remove_mediaitem_creator_mediaitem_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='creators',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.creator'),
            preserve_default=False,
        ),
    ]
