# Generated by Django 6.0.1 on 2026-08-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_contact_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creator',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
