# Generated by Django 6.0.1 on 2026-08-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0031_creator_tiktok_creator_website_creator_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='website',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='youtube',
        ),
    ]
